apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: database
spec:
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: dbport
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-db-secrets
  namespace: database
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mongo-db-secrets"    # AWS Secrets Manager secret name
        objectType: "secretsmanager"
        jmesPath:
          - path: "dbuser"
            objectAlias: "dbuser"
          - path: "dbpass"
            objectAlias: "dbpass"
  secretObjects:                          # Add this
    - secretName: mongo-db-secrets-csi    # Name of the Kubernetes Secret
      type: Opaque
      data:
        - objectName: "dbuser"            # Matches jmesPath objectAlias
          key: dbuser                     # Key in the Kubernetes Secret
        - objectName: "dbpass"            # Matches jmesPath objectAlias
          key: dbpass                     # Key in the Kubernetes Secret
