apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  labels:
    name: admin-api
  namespace: admin
spec:
  selector:
    matchLabels:
      app: admin-api
      module: admin
  template:
    metadata:
      labels:
        app: admin-api
        module: admin
    spec:
      serviceAccountName: admin-service-account
      nodeSelector:
        module: admin
      containers:
      - image: {{ECR_REGISTRY}}/admin-api:{{IMAGE_TAG}}
        name: admin-api
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 1025
          name: http
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: admin-api-secrets-csi
                key: connectionstring
          - name: PORT 
            value: "1025"
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 1025
          initialDelaySeconds: 30
          timeoutSeconds: 10
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "admin-api-secrets-provider" 
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: admin-api-secrets-provider
  namespace: admin
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "admin-api-secrets"  # AWS Secrets Manager secret name
        objectType: "secretsmanager"
        jmesPath:
          - path: "connectionstring"
            objectAlias: "connectionstring"
  secretObjects:                      # Add this section
    - secretName: admin-api-secrets-csi  # Name of the Kubernetes Secret
      type: Opaque
      data:
        - objectName: "connectionstring"  # Matches jmesPath objectAlias
          key: connectionstring          # Key in the Kubernetes Secret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api-svc
  namespace: admin
spec:
  type: NodePort
  selector:
    app: admin-api
    module: admin
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 32003
